// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Entity = __t.object("Entity", {
  id: __t.string(),
  worldId: __t.string(),
  data: __t.string(),
});
export type Entity = __Infer<typeof Entity>;

export const Goal = __t.object("Goal", {
  worldId: __t.string(),
  characterId: __t.string(),
  targetId: __t.string(),
});
export type Goal = __Infer<typeof Goal>;

export const Metadata = __t.object("Metadata", {
  id: __t.string(),
  schemaVersion: __t.u32(),
});
export type Metadata = __Infer<typeof Metadata>;

export const Participant = __t.object("Participant", {
  id: __t.string(),
  worldId: __t.string(),
  identity: __t.identity(),
});
export type Participant = __Infer<typeof Participant>;

export const Proposal = __t.object("Proposal", {
  id: __t.string(),
  worldId: __t.string(),
  actor: __t.identity(),
  operation: __t.string(),
  status: __t.string(),
});
export type Proposal = __Infer<typeof Proposal>;

export const World = __t.object("World", {
  id: __t.string(),
  owner: __t.identity(),
  revision: __t.u32(),
  schemaVersion: __t.u32(),
});
export type World = __Infer<typeof World>;

export const WorldEvent = __t.object("WorldEvent", {
  id: __t.string(),
  worldId: __t.string(),
  revision: __t.u32(),
  actor: __t.identity(),
  summary: __t.string(),
  snapshot: __t.string(),
  requestId: __t.string(),
});
export type WorldEvent = __Infer<typeof WorldEvent>;

export const WorldRule = __t.object("WorldRule", {
  id: __t.string(),
  worldId: __t.string(),
  data: __t.string(),
});
export type WorldRule = __Infer<typeof WorldRule>;

